include:
  - project: library/ci-templates
    ref: main
    file: /docker-image.yml
  - project: library/ci-templates
    ref: main
    file: /jobs/lint.yml

shellcheck:
  extends: .shellcheck
  variables:
    SHELL_FILES: restore-letsencrypt.sh update-k8s-secret.sh
