stages:
  - build
  - push
  - cleanup

variables:
  AFTER_SCRIPT_IGNORE_ERRORS: "true"
  IMAGE_NAME: $HARBOR_HOST/library/$CI_PROJECT_NAME
  
build:
  image: docker:27.0.3
  stage: build
  services:
    - docker:27.0.3-dind
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker buildx create --use --name builder_$CI_PROJECT_NAME
    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG -t $IMAGE_NAME:latest .

push:
  stage: push
  image: docker:27.0.3
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  services:
    - docker:27.0.3-dind
  script:
    - docker buildx create --use --name builder_$CI_PROJECT_NAME
    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG -t $IMAGE_NAME:latest --push . 
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cleanup-job:
  stage: cleanup
  image: docker:27.0.3
  services:
    - docker:27.0.3-dind
  allow_failure: true
  script:
    - docker buildx stop builder_$CI_PROJECT_NAME
    - docker buildx rm builder_$CI_PROJECT_NAME
  when: always

